# Generated by Django 5.0.3 on 2024-04-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gradregistrationModel',
            fields=[
                ('infoID', models.AutoField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=60)),
                ('firstname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=60)),
                ('department', models.CharField(max_length=100)),
                ('matricNum', models.CharField(max_length=30)),
                ('parentLastname', models.CharField(max_length=60)),
                ('parentFirstname', models.CharField(max_length=60)),
                ('parentEmail', models.EmailField(max_length=254)),
                ('parentPhone', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'registrationInfo_tbl',
            },
        ),
    ]
